### ISSUE TITLE
9.0.1 Release Info 

### ISSUE THREAD

**Issue by genu** [Joomla-Bible-Study/Joomla-Bible-Study#159]
### Minimum Requirements
**Joomla Version:** 3.4.x+

### New Features
- [x] All views are responsive using Bootstrap (https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/59)
- [x] New server/folder system (https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/284)
- [x] Ability to add topics on the study page. (#118)
- [x] Allow filters for series list menu item. (#267)
- [x] Image system. (#128)
- [x] And Lightbox popup for Media Player system. (#85)
- [x] New Jloader at head of component. (#79)
- [x] New file uploader system. (#132)
- [x] Media image converter (https://github.com/Joomla-Bible-Study/Joomla-Bible-Study/issues/610)
- [x] Archiving feature for older studies and media files

### Fixed Bugs
- [x] Podcast does not give proper path to image. (#268)
- [x] Joomla's discover doesn't find component. (#145)
- [x] Frontend new Media file: language is missing -> no podcast entry (?). (#266)
- [x] Date is one day off. (#263)
- [x] Download counter does not work. (#176)
- [x] Frontend Study admin: No template found. (#165)
- [x] CSS update error on install (#157)
- [x] Topics Drop down on studies list does not sort properly (#154)
- [x] Inside of popup player height won't adjust. (#83)
- [x] Fixed Donate button to PayPal on administration side cpanel (#640)
- [x] Fix install stepper showing proper steps and working through them in a timely manner. (#649)

### Refactoring
- [x] Migrated expert template code into actual template files using JBS Templatecode method (#645)
- [x] Removed most css as bootstrap and site template now determines look
- [x] Move FixAssets to a steeper to help with timeouts (#650)
